name: CI

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Store variables
        run: |
          touch .env
          echo 'REACT_APP_APIKEY=${{ secrets.REACT_APP_APIKEY }}' >> .env
          echo 'REACT_APP_APPID=${{ secrets.REACT_APP_APPID }}' >> .env
          echo 'REACT_APP_AUTH_DOMAIN=${{ secrets.REACT_APP_AUTH_DOMAIN }}' >> .env
          echo 'REACT_APP_PROJECT_ID=${{ secrets.REACT_APP_PROJECT_ID }}' >> .env

      - name: Build
        run: |
          npm install
          npm run-script build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases@4.0.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: build
